### ISSUE TITLE
Missing header files

### ISSUE THREAD

**Issue by ndowens** [msharov/snownews#34]
Several C files are missing <linux/limits.h> file :  
setup.c interface.c main.c ui-support.c io-internal.c filters.c dialog.c cookies.c
netio.c is missing <sys/select.h>
main.c is also missing <linux/time.h>

**Comment by kouya** [comment]
Odd, thought it compiled just fine last time I tried. I will check when I get the chance. Currently not on a system I can do.

**Comment by msharov** [comment]
linux/limits.h and linux/time.h should never be included directly, being an obvious Linux dependency. Please post the build errors you get and the compiler version.

**Comment by msharov** [comment]
From the files mentioned it appears that the problem is with PATH_MAX definition, which is notoriously difficult to get. Some libc implementations go to some length to hide the definition until a secret #define is added. Currently, defining _GNU_SOURCE is the most reliable way of saying "just give me all the definitions already...", and because snownews was already using this in one file I am going to do it globally with commit 9d7ac4d48bf8289e2f10b07865b1ba64f9c08a9e.

This should fix your problem, although I of course can't verify it; no special workarounds are needed on a normal linux platform. If it keeps failing for you, please post build errors. You may also need to search for PATH_MAX in your libc's headers and tell me what magic constant needs to be defined.
