### ISSUE TITLE
Makefile/Config.mk.in does not honor CFLAGS/LDFLAGS set by the user

### ISSUE THREAD

**Issue by ryandesign** [msharov/snownews#43]

**Comment by msharov** [comment]
Closed by commit 268ef84660c03df29e8f155c3570092add1596cd

Instead of having configure set the CFLAGS, the Makefile now will correctly take CFLAGS from the environment, when set as argument (e.g. `make CFLAGS="-w" install`) or by using `make -e`, allowing an override without overwriting the important flags.
