### ISSUE TITLE
Some feeds only loading first line of items

### ISSUE THREAD

**Issue by katp32** [msharov/snownews#52]
Some feeds (such as https://hackaday.com/blog/feed/) seem to only load the first line of the article, despite the entire article being encoded in the feed. This makes it impossible to read the news item.

**Comment by msharov** [comment]
The hackaday feed does encode a larger version of the article, but it is inside a &lt;content:encoded&gt; tag, which is not part of the [RSS specification](https://www.rssboard.org/rss-specification). While I'm not entirely opposed to supporting nonstandard features, it does not seem warranted to do so for just one feed. The other feeds I have that supply full article text do so in the &lt;description&gt; tag, which is what snownews displays. The hackaday feed only puts one line there with "read more", so that is all you see.
