### ISSUE TITLE
Support for special characters

### ISSUE THREAD

**Issue by Hamburgefonts** [msharov/snownews#78]
characters like: ä, ü, ö are shown as Ã¤, Ã¼, Ã¶. But also characters like , “, ”, °, –, and — are shown as question marks. maybe there is a simple fix for this like adding "charset=utf-8" somewhere.

<img width="300" alt="Bildschirmfoto 2022-08-03 um 14 59 56" src="https://user-images.githubusercontent.com/31579271/182615153-65e29eea-0c44-4680-a3af-13bf119ad2e7.png"> <img width="326" alt="Bildschirmfoto 2022-08-03 um 15 10 24" src="https://user-images.githubusercontent.com/31579271/182615958-631f81ac-1ff4-4df4-bbb4-197dfe178f24.png">

**Comment by msharov** [comment]
This is a locale configuration problem on your end. Snownews supports only utf8 and your locale is likely set to some legacy german encoding. Detailed instructions on configuring locale should be provided by your OS; see, for example, my Arch distribution's [instructions](https://wiki.archlinux.org/title/Locale).

I was able to properly configure the locale and test snownews display of the help dialog, where ü was displayed correctly. I added `de_DE.UTF-8 UTF-8` to `/etc/locale.gen`. Ran `locale-gen`, and verified that `de_DE` was listed in `locale -a` output. Then I ran `LANG=de_DE.utf8 snownews`, and the UI came up in german, with the diacritics correctly drawn.

**Comment by Hamburgefonts** [comment]
your comment was very helpful. first thing first, since i forgot to mention it the first time, i am running macos 12.5 on a M1. other terminal based applications like mutt never had this problem displaying those chacacters so i assumed this was a snownews problem. 

i did run a `locale -a` and was able to find 4 german ones: de_DE.UTF-8, de_DE.ISO8859-15, de_DE.ISO8859-1 and de_DE. none of them worked for me. de_DE.ISO8859-1 was the only one being able to display lowercase ö,ü & ä but not the uppercase Ü in `A: Über Snownews`. also none of them could display previously mentioned punctuation not even `LANG=en_EN.utf8 snownews`

snownews is running flawlessly in german on my x220 thinkpad running arch. i just wanted to note this here as documentation for anyone experiencing similar problems. i probably won't look further into this since i have spend already a lot of time on this. thank you again mike for helping me out!

**Comment by msharov** [comment]
The reason mutt works is that it implements charset conversion, because in the ancient times there was no UTF8. snownews doesn't because it's a lot of work, and because nobody should be using anything other than UTF8 anyway. Yes, you get 1 byte/char encoding, but do you really care these days? Just go and buy a 10 terabyte hard drive or something. I certainly don't bother with KOIR8 for my russian.

So snownews just uses plain UTF8 output, and when your terminal is set to ISO charset mode, it prints the multiple bytes of the UTF8 as ISO chars, showing you multiple bytes of garbage. The correct lowercase umlauts output may simply be a coincidence.

The problems you keep having suggest that your terminal is not setup for UTF8. You may have to set some variables for this, like adding `XTerm*utf8: 1` to your `.Xdefaults`, if you are using xterm. You should also delete all non-UTF8 locales to help you find apps not configured for UTF8, and configure them.
